      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build, tag, and push image to ECR
        env:
          ECR_REPOSITORY: mywebapp
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
          echo "Image $ECR_REPOSITORY:$IMAGE_TAG pushed successfully."

      - name: Test container with environment variables
        run: |
          docker run -d \
            -e APP_ENV=prod \
            -e SECRET_KEY=${{ secrets.APP_SECRET }} \
            ${{ steps.login-ecr.outputs.registry }}/mywebapp:${{ github.run_number }}

